### PR TITLE
Only publish events when there is one subscriber

### PR DESCRIPTION
**Pull request by catenacyber**
Performance optimization

CC @artemdinaburg @ehennenfent

---
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/1388)

### CODE REVIEW

**Comment by catenacyber** [comment]
```
from manticore.native import Manticore
m = Manticore("examples/linux/binaries/multiple-styles", concrete_start='coldlikeminisoda')
m.verbosity(2)
m.run()
```
goes from 15 secondes to 7 seconds

**Comment by catenacyber** [comment]
`python3 -m cProfile test.py > symbolic_multsty_cprofile.txt`
Then 
`cat symbolic_multsty_cprofile.txt | awk '{print $2, $0}' | sort -n`
Showed 
```
0.442   1433803    0.442    0.000    0.442    0.000 weakref.py:371(_commit_removals)
0.460 302283/302117    0.460    0.000   14.148    0.000 event.py:120(_publish)
0.564    258526    0.564    0.000    1.231    0.000 helpers.py:13(issymbolic)
0.603   1433807    0.603    0.000    0.603    0.000 _weakrefset.py:16(__init__)
0.677    302283    0.677    0.000    1.019    0.000 event.py:107(_check_event)
0.822   1433807    0.822    0.000    1.089    0.000 _weakrefset.py:20(__enter__)
0.888   1433808    0.888    0.000    1.153    0.000 event.py:102(_get_signal_bucket)
0.993     17371    0.993    0.000    0.993    0.000 {built-in method posix.read}
1.228   1433807    1.228    0.000    1.899    0.000 _weakrefset.py:26(__exit__)
2.968   2565323    2.968    0.000    6.755    0.000 weakref.py:438(items)
3.796 1433803/302117    3.796    0.000   12.670    0.000 event.py:126(_publish_impl)
```
And now
```
0.252     41056    0.252    0.000    4.936    0.000 abstractcpu.py:824(decode_instruction)
0.268 268276/267984    0.268    0.000    0.748    0.000 <frozen importlib._bootstrap>:1009(_handle_fromlist)
0.296    253367    0.296    0.000    0.563    0.000 memory.py:734(map_containing)
0.348   2259659    0.348    0.000    0.348    0.000 {built-in method builtins.isinstance}
0.408    126443    0.408    0.000    0.436    0.000 x86.py:469(__contains__)
0.409    165877    0.409    0.000    1.352    0.000 memory.py:847(access_ok)
0.419     67331    0.419    0.000    3.497    0.000 memory.py:1026(read)
0.528    258526    0.528    0.000    1.189    0.000 helpers.py:13(issymbolic)
0.938     17371    0.938    0.000    0.938    0.000 {built-in method posix.read}
```

**Comment by disconnect3d** [comment]
Hey, that looks like a really nice improvement.

The ethereum test suite failed for some reason and didn't give a log output, I've hit rebuilt there.

**Comment by catenacyber** [comment]
Hmm, I do not know why Travis is grey...

**Comment by catenacyber** [comment]
@feliam 
I thought my patch was too simple and was expecting the tests to fail at some point in a case like this.
Isn't there a test case for what you described ?

**Comment by feliam** [comment]
Move __sub_events__ to init.
        self.__sub_events__ = set()

In anycase this is an improvement because it avoids publishing events that have no subscriptions anywhere. (apparently there are a few events published that are not used at all)

**Pull request merged**
