### PR TITLE
Sha3 rework and performance enhancements

### LINKED ISSUE #1079: MSTORE8 tries to write a 256 bit value: it must extract a byte
https://github.com/trailofbits/manticore/blob/8142472c50617c130151ce701bb67a7f98972708/manticore/platforms/evm.py#L1125-L1131

### PR DESCRIPTION
**Pull request by feliam**
Sha3 trick improvements
Mini performance enhacements
Mini docstring enhancements

fixes #1079 

This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/1031)

### CODE REVIEW

**Comment by disconnect3d** [comment]
___
*[manticore/ethereum.py, line 470 at r1](https://reviewable.io/reviews/trailofbits/manticore/1031#-LKNi7959lbCjaqTWiZN:-LKNsbHl2ojaII6wF3Za:blcbjhm) ([raw file](https://github.com/trailofbits/manticore/blob/7be4bf1fab1beb50184223435011d19d241c7408/manticore/ethereum.py#L470)):*
<details><summary><i>Previously, disconnect3d (Disconnect3d) wrote…</i></summary><blockquote>

Should use triple quotes instead of apostrophes ;f
also the indent is not needed
</blockquote></details>

or just `"""Detects unused return value from internal transactions"""` anyway I see that we use apostrophes in half of the codebase and quotes in the other :<

**Comment by feliam** [comment]
___
*[manticore/platforms/evm.py, line 167 at r3](https://reviewable.io/reviews/trailofbits/manticore/1031#-LLAz8iH2h3F7ogP6qGd:-LLBDtbRETmZ3YxbUEr0:b1ceylr) ([raw file](https://github.com/trailofbits/manticore/blob/ace61422ae920ef69361b06951dbc6b4f43014a5/manticore/platforms/evm.py#L167)):*
> ```
> InvalidOpcode
> ```
Yeah 'THROW' is for InvaliOpcode, OOG, StackOverflow, StackUnderflow. All have same behavior/semantics.

**Comment by feliam** [comment]
___
*[manticore/ethereum.py, line 491 at r3](https://reviewable.io/reviews/trailofbits/manticore/1031#-LLB6TtkE1V9NvxYGo90:-LLBcWBgD6lie962eddC:b-ykhmsv) ([raw file](https://github.com/trailofbits/manticore/blob/e64eda1a24f9f4619c734401b071e11994b008cd/manticore/ethereum.py#L491)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

is the Ref class unused now? should we rm?
</blockquote></details>

Yessss. 
Event arguments are 100% read only now.
All changes on the state are via API over state/platform.

**Comment by feliam** [comment]
___
*[manticore/ethereum.py, line 2199 at r3](https://reviewable.io/reviews/trailofbits/manticore/1031#-LLBAKhsCOeQ3Ft3ZssJ:-LLBdSGf6ZTGdG3MjRVB:buuxde8) ([raw file](https://github.com/trailofbits/manticore/blob/ace61422ae920ef69361b06951dbc6b4f43014a5/manticore/ethereum.py#L2199)):*
> ```
>  _on_symbolic_sha3_callback(self, state,
> ```
Would it be more clear to just raise TerminateState? so you know it breaks there?

**Comment by feliam** [comment]
___
*[manticore/ethereum.py, line 500 at r1](https://reviewable.io/reviews/trailofbits/manticore/1031#-LKNiyTj6VCBZ8UuLlEH:-LLG_NDi0MG6f81aWX0m:bcp3a1x) ([raw file](https://github.com/trailofbits/manticore/blob/7be4bf1fab1beb50184223435011d19d241c7408/manticore/ethereum.py#L500)):*
> ```
>         for taint in self._get_retval_taints(state):
>             id_val = taint[7:]
> ```
https://github.com/trailofbits/manticore/issues/1107

**Pull request merged**
