### PR TITLE
Rewrite tests to be more compact

### PR DESCRIPTION
**Pull request by catenacyber**
See discussion in #1120 
Idea comes from @disconnect3d

---
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/1146)

### CODE REVIEW

**Comment by catenacyber** [comment]
And new commits as suggested by @feliam, so we get more than 10k deleted lines :-)

**Comment by catenacyber** [comment]
Helper script is 
```
import re

f = open("test_x86.py", "r")
f2 = open("test_x86_sub.py", "w")

instr = ""
addressB = 0
addressC = 0
reordered = []

for l in f.readlines():
    #m1 = re.search('mem\[(0x[0-9a-f]+)\] = \'(.*)\'', l)
    m1 = re.search('self.assertEqual\(mem\[(0x[0-9a-f]+)\], \'(.*)\'\)', l)
    if m1 != None:
        #print m1.group(1), m1.group(2)
        if len(instr) == 0:
            instr = ["b'%s'" % m1.group(2)]
            addressB = int(m1.group(1), 16)
            addressC = addressB
            reordered = [l]
        else:
            reordered.append(l)
            if int(m1.group(1), 16) == addressC + 1:
                instr.append("b'%s'" % m1.group(2))
                addressC = addressC + 1
            elif int(m1.group(1), 16) == addressC - 1:
                addressC = addressC - 1
                addressB = addressC
                instr.prepend("b'%s'" % m1.group(2))
            else:
                f2.write("        self.assertEqual(mem[0x%x:0x%x], [%s])\n" % (addressB,addressB+len(instr), ",".join(instr)))
                instr = ["b'%s'" % m1.group(2)]
                addressB = int(m1.group(1), 16)
                addressC = addressB
                reordered = [l]
                #print "fail",int(m1.group(1), 16), addressC
    else:
        if len(instr) > 0:
            #self.assertEqual(mem[0x8065f84:0x8065f88], [b'\x66', b'\x0f', b'\xde', b'\xe3'])
            f2.write("        self.assertEqual(mem[0x%x:0x%x], [%s])\n" % (addressB,addressB+len(instr), ",".join(instr)))
            #print sorted(reordered)
            #for l2 in sorted(reordered):
            #    f2.write(l2)
            instr = ""
            reordered = []
        f2.write(l)

f.close()
f2.close()
```

**Comment by disconnect3d** [comment]
Let me review it in 1-2 days :P.

**Comment by disconnect3d** [comment]
@mossberg hmm... how can we trigger travis build here? It's `trigger build` menu shows only our repo's branches :s.

**Comment by feliam** [comment]
Should not we update https://github.com/trailofbits/manticore/blob/master/tests/auto/make_tests.py
so any new generated test is similar.

**Comment by mossberg** [comment]
Maybe we can trigger it on the pull requests page of Travis?

**Comment by disconnect3d** [comment]
Bump?

**Comment by catenacyber** [comment]
@disconnect3d @feliam I did not find how to use `make_tests.py`
My guess is that it is linux specific with the gdb magic in `make_dump.py`
These scripts look deprecated as they do not support python3

So, I can do a "blind" path, ie without testing it or leave this be as it is
PS : I just pushed compacting other tests files

**Comment by disconnect3d** [comment]
@catenacyber hm... can we ask you to dive into those scripts, make them py3 compatible and apply the changes we mentioned before into them?

**Comment by catenacyber** [comment]
Hmm, this looks complicated to get running on my environment (MacOS rather than python3 I guess)
Here is a not-fully-tested patch for make_tests.py

**Comment by mossberg** [comment]
i just merged with master and resolved conflicts; let's just forget about updating make_tests.py for now, and merge this 🚢

**Pull request merged**
