### PR TITLE
Better plugin context management.

### PR DESCRIPTION
**Pull request by feliam**
Internal, vs external transactions.
Example UseDef logging plugin for evm.

---
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/730)

### CODE REVIEW

**Comment by mossberg** [comment]
what were you testing use_def.py with such that you needed internal transactions? there are only human transactions in that C contract?

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[examples/evm/use_def.py, line 1 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NJ40_5CLNQJA-NPOi:-L4NJ40_5CLNQJA-NPOj:b-kpofyu) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/examples/evm/use_def.py#L1)):*
> ```Python
> from manticore.ethereum import ManticoreEVM, Plugin
> ```

i'm not sure if the name `use_def.py` is accurate for this

---

*[examples/evm/use_def.py, line 64 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NH2Qh3jYn5esxORL9:-L4NH2Qh3jYn5esxORLA:bwzoq2t) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/examples/evm/use_def.py#L64)):*
> ```Python
>         offsets = state.solve_n(offset, 3000)
>         with self.locked_context('storage_writes', dict) as storage_writes:
>             contract_name, function_name = (md.name, md.get_func_name(r))
> ```

we could use a tuple variable for `(contract_name, function_name)` and use that instead of copy-pasting it 3 times!

---

*[manticore/manticore.py, line 221 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NA4Q4kziD2nBKOw-B:-L4NA4Q4kziD2nBKOw-C:b-az469g) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/manticore.py#L221)):*
> ```Python
>                     if event_name not in all_events:
>                         logger.warning("There is no event name %s for callback on plugin type %s", event_name, type(plugin) )
>             for event_name in all_events:
> ```

since we only emit warnings in this block, let's remove the `if logger.isEnabledFor(logging.DEBUG)` check above. those warnings should always be printed.

also, i don't think we need this block. I think plugins should be allowed to have helper methods or whatever, that don't have _callback or on/will/did_

---

*[manticore/core/plugin.py, line 28 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NBnV2jdUnf_2CFZ1T:-L4NBnV2jdUnf_2CFZ1U:b-neobei) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/core/plugin.py#L28)):*
> ```Python
> 
>     @property
>     def context(self):
> ```

i'm a little confused on this vs self.locked_context. aren't we never supposed to use this context directly without locked_content?

---

*[manticore/core/plugin.py, line 31 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NBgPOIJQ0UfI3JB-d:-L4NBgPOIJQ0UfI3JB-e:b-3et3vx) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/core/plugin.py#L31)):*
> ```Python
>         ''' Convenient access to shared context '''
>         plugin_context_name = str(type(self))
>         if plugin_context_name not in plugin_context_name:
> ```

what is this line supposed to do? this will always be false?

---

*[manticore/platforms/evm.py, line 1951 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4ND4HoDCp6w32xH0fF:-L4N54XOaEaLkhBH60mM:b-e43arf) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/platforms/evm.py#L1951)):*
> ```Python
>     @property
>     def internal_transactions(self):
>         n = len(self._transactions)
> ```

should probably use a better name than `n`

---

*[manticore/platforms/evm.py, line 1952 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NDFYhQ3EIdfpcDadX:-L4NDFYhQ3EIdfpcDadY:b5k6hcl) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/platforms/evm.py#L1952)):*
> ```Python
>     def internal_transactions(self):
>         n = len(self._transactions)
>         for _ in range( len (self._internal_transactions), n):
> ```

I think this design with the list of lists is pretty confusing, we should at least have a comment in the docstring describing it. i think we should brainstorm some alternative designs. maybe we could use an OrderedDict for everything?

```
{
first_tx: [internal1, internal2],
second_tx: [],
third_tx: [internal3],
...
}
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730#-:-L4NC_qmwgd0It7OdEcy:b-nzmy4m)*

**Comment by mossberg** [comment]
Review status: 3 of 4 files reviewed at latest revision, 12 unresolved discussions.

---

*[manticore/manticore.py, line 215 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4b9LiNSL4GJZ6kdrvP:-L4b9LiNSL4GJZ6kdrvQ:b3hvlcj) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/manticore.py#L215)):*
> ```Python
>                 self.subscribe(event_name, callback)
> 
>         if logger.isEnabledFor(logging.DEBUG):
> ```

i think we should rm this `if` line; it doesn't make sense, because there are no `logger.debug` calls in the body, only `logger.warning`. these warnings should always show

---

*[manticore/manticore.py, line 220 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4b9igbcjartO_gg8Bi:-L4b9igbcjartO_gg8Bj:bwnox7s) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/manticore.py#L220)):*
> ```Python
>                     event_name = callback_name[:-9]
>                     if event_name not in all_events:
>                         logger.warning("There is no event name %s for callback on plugin type %s", event_name, type(plugin) )
> ```

i think we should change `type(plugin)` to be `plugin.__class__.__name__`. currently the output looks like this, which i don't think looks very good at the end

```
2018-02-05 13:09:49,192: [62536] m.manticore:WARNING: Pluging methods name 'did_evm_read_storage()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedStorage'>
2018-02-05 13:09:49,192: [62536] m.manticore:WARNING: Pluging methods name 'did_evm_write_storage()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedStorage'>
2018-02-05 13:09:49,193: [62536] m.manticore:WARNING: Pluging methods name 'did_evm_write_memory()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedMemory'>
2018-02-05 13:09:49,193: [62536] m.manticore:WARNING: Pluging methods name 'did_evm_read_memory()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedMemory'>
```

---

*[manticore/manticore.py, line 220 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4bBDkcaQIrLyKOxnXq:-L4bBDkcaQIrLyKOxnXr:bder3ho) ([raw file](https://github.com/trailofbits/manticore/blob/547c4825aa4f93ee962b3541b1e494fa3c716f2a/manticore/manticore.py#L220)):*
> ```Python
>                     event_name = callback_name[:-9]
>                     if event_name not in all_events:
>                         logger.warning("There is no event name %s for callback on plugin type %s", event_name, type(plugin) )
> ```

spelling: "event named"

---

*[manticore/manticore.py, line 228 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4bBGfpM4ObhfD18zcf:-L4bBGfpM4ObhfD18zcg:blcwm1z) ([raw file](https://github.com/trailofbits/manticore/blob/547c4825aa4f93ee962b3541b1e494fa3c716f2a/manticore/manticore.py#L228)):*
> ```Python
>                                plugin_method_name.startswith('will_') or \
>                                plugin_method_name.startswith('did_'):
>                                 logger.warning("Pluging methods name '%s()'should end with '_callback' on plugin type %s", plugin_method_name, type(plugin) )
> ```

"Pluging" -> "Plugin"

---

*[manticore/manticore.py, line 228 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4bBL3nboc9kkWSiyhx:-L4bBL3nboc9kkWSiyhy:b-f2z7d6) ([raw file](https://github.com/trailofbits/manticore/blob/547c4825aa4f93ee962b3541b1e494fa3c716f2a/manticore/manticore.py#L228)):*
> ```Python
>                                plugin_method_name.startswith('will_') or \
>                                plugin_method_name.startswith('did_'):
>                                 logger.warning("Pluging methods name '%s()'should end with '_callback' on plugin type %s", plugin_method_name, type(plugin) )
> ```

missing a space before "should"

---

*[manticore/manticore.py, line 228 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4bBSQ4gYj4SHOSatz-:-L4bBSQ4gYj4SHOSatz0:b-c863b3) ([raw file](https://github.com/trailofbits/manticore/blob/547c4825aa4f93ee962b3541b1e494fa3c716f2a/manticore/manticore.py#L228)):*
> ```Python
>                                plugin_method_name.startswith('will_') or \
>                                plugin_method_name.startswith('did_'):
>                                 logger.warning("Pluging methods name '%s()'should end with '_callback' on plugin type %s", plugin_method_name, type(plugin) )
> ```

"on plugin type" -> "on plugin" ? i think it's better phrasing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by mossberg** [comment]
While we're here, I noticed a few issues:

- UnitializedMemory/Storage has a type in the name -> "UninitializedMemory"
- They don't put `_callback` at the end of their method names

```

2018-02-05 13:21:55,138: [63492] m.manticore:WARNING: Pluging methods name 'did_evm_read_storage()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedStorage'>
2018-02-05 13:21:55,138: [63492] m.manticore:WARNING: Pluging methods name 'did_evm_write_storage()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedStorage'>
2018-02-05 13:21:55,138: [63492] m.manticore:WARNING: Pluging methods name 'did_evm_write_memory()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedMemory'>
2018-02-05 13:21:55,139: [63492] m.manticore:WARNING: Pluging methods name 'did_evm_read_memory()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedMemory'>
```

---

Reviewed 1 of 1 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730#-:-L4bCD8RpASRoFzfF5DP:b-iujhsp)*

**Comment by feliam** [comment]
> UnitializedS
Nice! found via the warning thing!


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730#-:-L4bEVxj0l92hZAokTRT:b-e6p4vi)*

**Comment by mossberg** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/core/plugin.py, line 28 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NBnV2jdUnf_2CFZ1T:-L4bP_8U8zEIQV9mQGkf:bvxb25n) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/core/plugin.py#L28)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

i'm a little confused on this vs self.locked_context. aren't we never supposed to use this context directly without locked_content?
</blockquote></details>

hmm...
If manticore is not running (after the run() concluded or before it has started) we can use manticore context. 
I imagine ppl maintaining the reference to the plugin and getting the interesting context out of the plugin object after the run.

Like this.. 
https://github.com/trailofbits/manticore/pull/730/files#diff-692517d4c39ee00d8174d33cfc7e40d7R102

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[examples/evm/use_def.py, line 64 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NH2Qh3jYn5esxORL9:-L4bjvzlTg39VRGiAx7j:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/examples/evm/use_def.py#L64)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

we could use a tuple variable for `(contract_name, function_name)` and use that instead of copy-pasting it 3 times!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/manticore.py, line 228 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4bBSQ4gYj4SHOSatz-:-L4bk6IJoB3F8TbltmzE:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/547c4825aa4f93ee962b3541b1e494fa3c716f2a/manticore/manticore.py#L228)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

"on plugin type" -> "on plugin" ? i think it's better phrasing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/manticore.py, line 228 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4bBL3nboc9kkWSiyhx:-L4bk4RyREOJg9x7CPjo:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/547c4825aa4f93ee962b3541b1e494fa3c716f2a/manticore/manticore.py#L228)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

missing a space before "should"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/manticore.py, line 220 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4b9igbcjartO_gg8Bi:-L4bk2PHxprLdagEFdWs:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/manticore.py#L220)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

i think we should change `type(plugin)` to be `plugin.__class__.__name__`. currently the output looks like this, which i don't think looks very good at the end

```
2018-02-05 13:09:49,192: [62536] m.manticore:WARNING: Pluging methods name 'did_evm_read_storage()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedStorage'>
2018-02-05 13:09:49,192: [62536] m.manticore:WARNING: Pluging methods name 'did_evm_write_storage()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedStorage'>
2018-02-05 13:09:49,193: [62536] m.manticore:WARNING: Pluging methods name 'did_evm_write_memory()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedMemory'>
2018-02-05 13:09:49,193: [62536] m.manticore:WARNING: Pluging methods name 'did_evm_read_memory()'should end with '_callback' on plugin type <class 'manticore.ethereum.UnitializedMemory'>
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/manticore.py, line 215 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4b9LiNSL4GJZ6kdrvP:-L4bk0bne3lDVsjUAWUJ:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/manticore.py#L215)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

i think we should rm this `if` line; it doesn't make sense, because there are no `logger.debug` calls in the body, only `logger.warning`. these warnings should always show
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/core/plugin.py, line 31 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NBgPOIJQ0UfI3JB-d:-L4bkKVVzJp32VXGyTcn:b-v5d6oe) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/core/plugin.py#L31)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

what is this line supposed to do? this will always be false?
</blockquote></details>

FIxed. It just initializes to a default dict.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/core/plugin.py, line 31 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NBgPOIJQ0UfI3JB-d:-L4bkRp4RxOAbtqTGcaF:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/core/plugin.py#L31)):*
<details><summary><i>Previously, feliam (feliam) wrote…</i></summary><blockquote>

FIxed. It just initializes to a default dict.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by mossberg** [comment]
Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[manticore/manticore.py, line 234 at r4](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4cS2kQ1XHcl86mLSiB:-L4cS2kQ1XHcl86mLSiC:b4zia9d) ([raw file](https://github.com/trailofbits/manticore/blob/b090e9ad55f22a6679e9894bcf11a35df690dbf2/manticore/manticore.py#L234)):*
> ```Python
>                         not plugin_method_name.startswith('will_') and \
>                         not plugin_method_name.startswith('did_'):
>                             logger.warning("Plugin methods name '%s()' should start with 'on_', 'will_' or 'did_' on plugin %s", plugin_method_name, type(plugin).__name__)
> ```

sp: named

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by mossberg** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[manticore/core/plugin.py, line 28 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NBnV2jdUnf_2CFZ1T:-L4gcjbLtdCeM927adBF:b-ey2bxx) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/core/plugin.py#L28)):*
<details><summary><i>Previously, feliam (feliam) wrote…</i></summary><blockquote>

hmm...
If manticore is not running (after the run() concluded or before it has started) we can use manticore context. 
I imagine ppl maintaining the reference to the plugin and getting the interesting context out of the plugin object after the run.

Like this.. 
https://github.com/trailofbits/manticore/pull/730/files#diff-692517d4c39ee00d8174d33cfc7e40d7R102

</blockquote></details>

i see! could we change it to one interface that automatically does the right then based on whether manticore is running or not? this should be doable, since the plugin has access to the Manticore object?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/platforms/evm.py, line 1952 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NDFYhQ3EIdfpcDadX:-L4wD-brV4erq61t40-7:b21wcxh) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/platforms/evm.py#L1952)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

I think this design with the list of lists is pretty confusing, we should at least have a comment in the docstring describing it. i think we should brainstorm some alternative designs. maybe we could use an OrderedDict for everything?

```
{
first_tx: [internal1, internal2],
second_tx: [],
third_tx: [internal3],
...
}
```
</blockquote></details>

Each human initiated transaction has a list of internal transactions.
I'd say let's start with this and leave the brainstorm for a different PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/core/plugin.py, line 28 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NBnV2jdUnf_2CFZ1T:-L4wDZt22-TXlUjmRzDC:b-80cb9g) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/core/plugin.py#L28)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

i see! could we change it to one interface that automatically does the right then based on whether manticore is running or not? this should be doable, since the plugin has access to the Manticore object?
</blockquote></details>

Does not it do the right thing already? 
It will print a warning if used wrong
https://github.com/trailofbits/manticore/blob/master/manticore/manticore.py#L294-L301

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by mossberg** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[manticore/core/plugin.py, line 28 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NBnV2jdUnf_2CFZ1T:-L4wPbphj2r73Co4RoKn:b-it6o9y) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/core/plugin.py#L28)):*
<details><summary><i>Previously, feliam (feliam) wrote…</i></summary><blockquote>

Does not it do the right thing already? 
It will print a warning if used wrong
https://github.com/trailofbits/manticore/blob/master/manticore/manticore.py#L294-L301
</blockquote></details>

ok, i see!

---

*[manticore/platforms/evm.py, line 2345 at r5](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4wQ5ewsHd0pek4v8bP:-L4wQ5ewsHd0pek4v8bQ:b-44hacy) ([raw file](https://github.com/trailofbits/manticore/blob/d25f7321b1e9a283f393ee3ebfea22c12a0ca08a/manticore/platforms/evm.py#L2345)):*
> ```Python
> 
>             self._transactions.append(tx)
>         else:            
> ```

nit, a little whitespace at the end of this line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by feliam** [comment]
*[manticore/core/plugin.py, line 28 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NBnV2jdUnf_2CFZ1T:-L5KpIi4vfy2cDUAE8qy:bom27qw) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/manticore/core/plugin.py#L28)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

ok, i see!
</blockquote></details>

I set this at Done. then.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Comment by mossberg** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730#-:-L5KwcyA-spUHJGd44Hm:bnfp4nl)*

**Comment by feliam** [comment]
*[examples/evm/use_def.py, line 1 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/730#-L4NJ40_5CLNQJA-NPOi:-L4bG_-FgxrH6Op8j97i:b-vl21pz) ([raw file](https://github.com/trailofbits/manticore/blob/43bd04530da67402772f966ce2499b55a760ddb8/examples/evm/use_def.py#L1)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

i'm not sure if the name `use_def.py` is accurate for this
</blockquote></details>

Any suggestion?  We do not have any good place to put the plugins yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/730)*

**Pull request merged**
