### PR TITLE
Manticore 0.1.7 Release

### PR DESCRIPTION
**Pull request by yan**
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/764)

### CODE REVIEW

**Comment by mossberg** [comment]
Reviewed 3 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[CHANGELOG.md, line 16 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/764#-L5zHgRr6VGQJ92n9aIB:-L5zHgRsgNYN4XHJEFTs:b65rhuc) ([raw file](https://github.com/trailofbits/manticore/blob/ca9cbb0143e38006af7212078b90bd9ed299821d/CHANGELOG.md#L16)):*
> ```Markdown
> - [alexanderholman](https://github.com/alexanderholman)
> 
> ### Added
> ```

also, new linux syscalls

---

*[CHANGELOG.md, line 18 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/764#-L5zHvRjsz0thWiDK5wT:-L5zHvRjsz0thWiDK5wU:b-yt9c91) ([raw file](https://github.com/trailofbits/manticore/blob/ca9cbb0143e38006af7212078b90bd9ed299821d/CHANGELOG.md#L18)):*
> ```Markdown
> ### Added
> 
> - Improved documentation on symbolic input
> ```

remove the word "Improved"?

---

*[CHANGELOG.md, line 22 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/764#-L5zHGpQYsBl5fpdalHw:-L5zHGpQYsBl5fpdalHx:bfd1ah2) ([raw file](https://github.com/trailofbits/manticore/blob/ca9cbb0143e38006af7212078b90bd9ed299821d/CHANGELOG.md#L22)):*
> ```Markdown
> ### Changed
> 
> - New "force" flag on memory APIs
> ```

i think we should explicitly say what APIs we're talking about. also maybe this should go under "Added"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/764)*

**Comment by mossberg** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 24 at r3](https://reviewable.io:443/reviews/trailofbits/manticore/764#-L63KGQ7mOQHZVI-9fCn:-L63KGQ89quNKQAxARS-:bc5v94m) ([raw file](https://github.com/trailofbits/manticore/blob/54a0acf95f019ab80605441694f170de86588990/CHANGELOG.md#L24)):*
> ```Markdown
> 
> 
> ### Changed
> ```

should rm this empty category

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/764)*

**Comment by yan** [comment]
Reviewed 1 of 7 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CHANGELOG.md, line 16 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/764#-L5zHgRr6VGQJ92n9aIB:-L63NWk0Bwj0c86iYIiq:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/ca9cbb0143e38006af7212078b90bd9ed299821d/CHANGELOG.md#L16)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

also, new linux syscalls
</blockquote></details>

Done.

---

*[CHANGELOG.md, line 24 at r3](https://reviewable.io:443/reviews/trailofbits/manticore/764#-L63KGQ7mOQHZVI-9fCn:-L63NTt0o2rh6goltDKV:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/54a0acf95f019ab80605441694f170de86588990/CHANGELOG.md#L24)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

should rm this empty category
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/764)*

**Comment by mossberg** [comment]
:lgtm: but let's make sure this is the last PR we merge before the release (in case we merge some other ones quickly today)

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/764#-:-L63OH_rpGdrJYvihmrv:b-bq8j6g)*

**Comment by mossberg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/764#-:-L63wkXvoKspNpbiyQSk:bnfp4nl)*

**Pull request merged**
