### PR TITLE
performance: faster program load with faster memory write

### PR DESCRIPTION
**Pull request by catenacyber**
I experienced it while loading a big program (200Mb)
After more than 10 minutes waiting, I saw that I was slowly looping in `write_bytes` in abstractcpu.py as the memory type is `FileMap` and not `AnonMap`

With this simple patch, it takes less than a minute.

### CODE REVIEW

**Comment by catenacyber** [comment]
No ideas why 2 tests fail... Any help ?

**Comment by ehennenfent** [comment]
The Unicorn tests are failing because only `cpu.write_bytes` emits the `did_write_memory` event, for which the Unicorn module has a subscribed callback that keeps memory states synced between Manticore and Unicorn. We do need to make sure that callback gets emitted anytime we write to memory, even if bypassing the CPU while doing so.
Mind you, `cpu.write_bytes` has a special "fast write" behavior specifically intended for copying memory maps into Unicorn, so if you bypass it to write directly to the memory map while loading a Linux binary, it'll make the regular emulation faster, but make the "fast forwarding" capabilities of the Unicorn module significantly less effective.

**Comment by catenacyber** [comment]
Thank you Eric.
Here is another proposal to achieve the same speed-up for `load` while not bypassing  `cpu.write_bytes` but rather relaxing the condition to go on the fast path.
But I am not sure if it has more side effects...

**Comment by ehennenfent** [comment]
Closing this & the other PR's that haven't been updated since 2019. Feel free to reopen if you're planning further updates.

**Pull request closed without merging**
