### PR TITLE
Fix evm RETURN implementation

### LINKED ISSUE #807: TypeError: unsupported operand type(s) for &: 'str' and 'int'
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (fceb48ce0cff29b5af31f0784c031574ff9e23e5)

### Python version

Python 2.7.14

### Summary of the problem

Type error when manticore runs a multi-contract solidity file.

### Step to reproduce the behavior

This is a small solidity contract to reproduce this issue:

```solidity
contract X {
    mapping(address => uint) private balance;
    function f(address z) returns (uint) {
      return balance[z];
    }
}

contract C {
  X y;
  function C() {
    y = new X();
    uint z = y.f(0);
  }
}
```

To reproduce, just execute:

```bash
$ manticore error.sol --contract C
```

### Expected behavior

It shouldn't crash.

### Actual behavior

```
2018-03-12 13:48:49,205: [23604] m.main:INFO: Beginning analysis
2018-03-12 13:48:49,834: [23604] m.c.executor:ERROR: Exception: unsupported operand type(s) for &: 'str' and 'int'
Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/core/executor.py", line 463, in run
    if not current_state.execute():
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 2178, in execute
    self.RETURN(ex.data)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 2418, in RETURN
    self.current.write_buffer(last_ex.out_offset, data[:size])
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 1804, in write_buffer
    self._store(offset+count, c)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 1197, in _store
    self.memory.write(address, [value])
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 302, in write
    self._concrete_write(address+offset, value[offset])
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 205, in _concrete_write
    assert value & ~(pow(2,self._value_size)-1) == 0 , "Not the correct size for a value"
TypeError: unsupported operand type(s) for &: 'str' and 'int'

2018-03-12 13:48:49,838: [23604] m.ethereum:INFO: Starting symbolic transaction: 1
2018-03-12 13:48:49,857: [23604] m.c.executor:ERROR: Exception: 
Traceback (most recent call last):
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/core/executor.py", line 463, in run
    if not current_state.execute():
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/core/state.py", line 126, in execute
    result = self._platform.execute()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 2166, in execute
    self._process_pending_transaction()
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/platforms/evm.py", line 2313, in _process_pending_transaction
    assert self.current is None or self.current.last_exception is not None
AssertionError

2018-03-12 13:48:49,873: [23604] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 0% | Terminated States: 0 | Alive States: 1
2018-03-12 13:48:49,880: [24124] m.ethereum:INFO: Generated testcase No. 0 - 
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 1282, in f
    self.terminate_state_id(state_id)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 740, in terminate_state_id
    self._generate_testcase_callback(state, 'test', last_exc.message)
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 1146, in _generate_testcase_callback
    summary.write(metadata.get_source_for(offset, at_runtime))
  File "/home/gustavo/.local/lib/python2.7/site-packages/manticore-0.1.7-py2.7.egg/manticore/ethereum.py", line 219, in get_source_for
    beg, size, _, _ = srcmap[asm_offset]
KeyError: 141L
2018-03-12 13:48:49,889: [23604] m.ethereum:INFO: Results in /home/gustavo/projects/audit-golem/mcore_z_FXXj
```

### PR DESCRIPTION
**Pull request by yan**
The `write_buffer` utility method (used by `RETURN`) previously tried storing a buffer byte-by-byte as `str`s. This didn't meet `_store`'s implicit contract of assuming that its `value` argument is an int or a bitvec. This pr ensures that byte type is correct.

Closes #807

---
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/808)

### CODE REVIEW

**Comment by mossberg** [comment]
thanks for the great pr description 🙏

**Comment by mossberg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_eth.py, line 106 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/808#-L7QTPy1RX3oLWczzFKH:-L7QTPy1RX3oLWczzFKI:b-m8lq98) ([raw file](https://github.com/trailofbits/manticore/blob/719dced0e6d51dc9092bceebd50ac3fb00b9be70/tests/test_eth.py#L106)):*
> ```Python
>                 contract_name="C", owner=owner, args=[x])
> 
>     def test_writebuffer_doesnt_raise(self):
> ```

for this style of test (and the one) above, it's basically an integration test. we already have some of these in test_binaries.py, should this go there instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/808)*

**Comment by yan** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_eth.py, line 106 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/808#-L7QTPy1RX3oLWczzFKH:-L7QYiZyNHTBoETvJ9Pk:b-iwn88) ([raw file](https://github.com/trailofbits/manticore/blob/719dced0e6d51dc9092bceebd50ac3fb00b9be70/tests/test_eth.py#L106)):*
<details><summary><i>Previously, mossberg (Mark Mossberg) wrote…</i></summary><blockquote>

for this style of test (and the one) above, it's basically an integration test. we already have some of these in test_binaries.py, should this go there instead?
</blockquote></details>

I briefly considered doing this, but both of these tests are multi-contract tests, which the scaffolding in `test_binaries.py` doesn't support yet. I'm fully on board in moving them there eventually. (can create an issue if you agree)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/808)*

**Comment by mossberg** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tests/test_eth.py, line 106 at r1](https://reviewable.io:443/reviews/trailofbits/manticore/808#-L7QTPy1RX3oLWczzFKH:-L7QZCbJ0URn4tEENUUQ:b9ciawq) ([raw file](https://github.com/trailofbits/manticore/blob/719dced0e6d51dc9092bceebd50ac3fb00b9be70/tests/test_eth.py#L106)):*
<details><summary><i>Previously, yan (Yan Ivnitskiy) wrote…</i></summary><blockquote>

I briefly considered doing this, but both of these tests are multi-contract tests, which the scaffolding in `test_binaries.py` doesn't support yet. I'm fully on board in moving them there eventually. (can create an issue if you agree)
</blockquote></details>

ok, sure, yes please create an issue (and mark it as help wanted, etc)!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/808#-:-L7QZwaFiQtUeSJoz1PO:bnfp4nl)*

**Pull request merged**
