### PR TITLE
Enforce black formatting

### PR DESCRIPTION
**Pull request by Tiecoon**
create a pyproject.toml so users don't have to worry about command line flags for black

---
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/1466)

### CODE REVIEW

**Comment by ekilmer** [comment]
Would be nice to propagate this to `.travis.yml` also. Should appear on [line 43](https://github.com/trailofbits/manticore/blob/a0966dca9b2243a1235afed9a431f00e69ad358c/.travis.yml#L43)

**Comment by ehennenfent** [comment]
@Tiecoon Just to make sure having a `pyproject.toml` in the root doesn't break the install process, can you run `pip install .` in a fresh virtual environment and make sure it works okay?

**Comment by Tiecoon** [comment]
it works fine here, unicorn still complains if i just pip install .[native], but it does that on master for me as well currently.

**Comment by Tiecoon** [comment]
i can figure out how to specify a build system in the pyproject.toml.

**Pull request merged**
