### PR TITLE
Refactor manticore and executor

### PR DESCRIPTION
**Pull request by disconnect3d**
This PR refactors a little bit executor and manticore and also adds a `--reraise-args` argument which simplifies some development like adding new archs.

---
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/761)

### CODE REVIEW

**Comment by yan** [comment]
Thanks again @disconnect3d! This PR includes a lot of cleanups, but I'm not sure that the main reason for this is a good direction. Expanding the command line interface to include debugging features might be cluttering up our already-long list of parameters, not to mention adding debugging features to public Executor API. I'm tempted to say if you want the exception to bubble up, just add a `raise` in your own tree while you're developing/debugging.

Thoughts @mossberg , @feliam ?

**Comment by disconnect3d** [comment]
I'm fine with not adding reraising to the codebase, so I will cancel those
changes.

**Comment by disconnect3d** [comment]
@yan Fixed - I have removed the `--reraise-errors` flag. If anyone wants to see changes related to it, those can be seen here https://github.com/disconnect3d/manticore/commit/d9e278ec998641aeb79019145340d567a9a9d7c8

**Comment by disconnect3d** [comment]
Bump: I have also fixed logger usages (i.e. use logger string formatting instead of formatting string manually).

**Comment by feliam** [comment]
I love the eradication of .format() in logging!

**Comment by disconnect3d** [comment]
Closing it as there is a better refactoring PR - https://github.com/trailofbits/manticore/pull/772
I will reopen a new one that will fix logging's `.format` after #772 is merged.

**Pull request closed without merging**
