### PR TITLE
Bump Node from 13.x to 16.x

### PR DESCRIPTION
**Pull request by G-11-P**

### CODE REVIEW

**Comment by ehennenfent** [comment]
Thanks for the PR! This seems to be passing tests okay, and puts us on a better-supported version of NPM. Just one thing - would you mind submitting the CLA so that we can merge this? It's linked [above](https://cla-assistant.io/trailofbits/manticore?pullRequest=2484)

**Review by G-11-P — COMMENTED** [review]
???

**Review by ehennenfent — APPROVED** [review]
Reverted some breaking changes to ci.yml (which look like a copy/paste error?) and this LGTM! Thanks for the PR.

**Comment by G-11-P** [comment]
Thank you awesome man i appreciate the assistance!

**Pull request merged**
