### PR TITLE
Update gas metering for calls to empty accounts

### PR DESCRIPTION
**Pull request by wolflo**
Addresses #1773, but is in need of some tests still.

Also, it brings up the related question of determining account existence. [EIP-161](https://eips.ethereum.org/EIPS/eip-161) defines an account as "*empty* when it has **no code** and **zero nonce** and **zero balance**." I'm not sure if existence in `EVM.world.accounts` ends up having the same meaning or not.

### CODE REVIEW

**Comment by ehennenfent** [comment]
Thanks for the PR! Just as an update, we're interested in merging this, but we've introduced a test regression that we're trying to eliminate before merging other PRs. You can track the progress of that here: #1776

**Comment by wolflo** [comment]
@ehennenfent thanks for the update. I can write some tests for it in the meantime, but it looks like most of the evm tests rely on the Ethereum VM test suite. My assumption is this isn't covered because the vm tests replace call execution with the `callcreates` item.

So, are python tests preferred for EVM changes, or additional GST-style tests?

**Comment by ehennenfent** [comment]
The particular style tests are written in doesn't matter so much as the time it takes to run them - in particular, we don't want to push the time for one build step above ~40m. Assuming that Python tests are easier, you could put them in `tests/ethereum`, which already has several miscellaneous EVM tests that fall under it.

**Comment by ehennenfent** [comment]
Hey there! We've fixed #1776 so I wanted to check in again. It looks like all this needs is a small regression test to ensure that gas is calculated correctly for the `CALL` instruction. I think `ethereum/test_general.py` and `ethereum/test_regressions.py` both have some similar tests that should be easily modifiable.

**Comment by wolflo** [comment]
Sorry I lost track of this a bit, but will add a test this week.

**Comment by wolflo** [comment]
@ehennenfent happy to make any changes or updates you can suggest. It doesn't seem like this branch is the source of the CI failures, but I can rebase or dig into the issue as well.

**Pull request merged**
