### PR TITLE
evm: Fix MUL overflow false positive

### LINKED ISSUE #714: Manticore detects a false positive integer overflow in a very simple contract
### OS / Environment

Distributor ID:	ArchLinux
Description:	ArchLinux
Release:	rolling-release

### Manticore version

Last revision (465c926a2e39d5daf1405711dac61b6ddd0a2527)

### Python version

Python 2.7.13

### Summary of the problem

Manticore detects a false positive integer overflow in a very simple contract.

### Step to reproduce the behavior

This is a small solidity contract to reproduce this issue:

```
contract C {
    function() {
        if (msg.data[0] == 1) {
            return;
        }else{
            return;
        }
    }
}
```

You can trigger this issue using the manticore cli:

```
$ manticore error.sol                                                                
```

### Expected behavior

It shouldn't detect an integer overflow.

### Actual behavior

```
2018-01-16 08:42:29,596: [13352] m.main:INFO: Beginning analysis
2018-01-16 08:42:29,633: [13352] m.ethereum:INFO: Starting symbolic transaction: 1
2018-01-16 08:42:29,969: [13352] m.ethereum:WARNING: Integer overflow at MUL instruction
2018-01-16 08:42:30,099: [13352] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-01-16 08:42:33,105: [13352] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-01-16 08:42:35,147: [13352] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 98% | Terminated States: 2 | Alive States: 2
2018-01-16 08:42:35,153: [13352] m.ethereum:INFO: Starting symbolic transaction: 2
2018-01-16 08:42:35,665: [13352] m.ethereum:INFO: Generated testcase No. 2 - REVERT
2018-01-16 08:42:39,842: [13352] m.ethereum:INFO: Generated testcase No. 3 - REVERT
2018-01-16 08:42:43,122: [13352] m.ethereum:INFO: Generated testcase No. 4 - REVERT
2018-01-16 08:42:47,779: [13352] m.ethereum:WARNING: Integer overflow at MUL instruction
2018-01-16 08:42:48,104: [13352] m.ethereum:INFO: Generated testcase No. 5 - REVERT
2018-01-16 08:42:51,469: [13352] m.ethereum:WARNING: Integer overflow at MUL instruction
2018-01-16 08:42:51,703: [13352] m.ethereum:INFO: Finished symbolic transaction: 2 | Code Coverage: 98% | Terminated States: 6 | Alive States: 4
2018-01-16 08:42:51,718: [13352] m.ethereum:INFO: Generated testcase No. 6 - STOP
2018-01-16 08:42:54,907: [13352] m.ethereum:INFO: Generated testcase No. 7 - STOP
2018-01-16 08:42:57,973: [13352] m.ethereum:INFO: Generated testcase No. 8 - STOP
2018-01-16 08:43:01,252: [13352] m.ethereum:INFO: Generated testcase No. 9 - STOP
2018-01-16 08:43:04,389: [13352] m.ethereum:INFO: Results in mcore_ttp4py
```

### PR DESCRIPTION
**Pull request by mossberg**
This implements a (more) correct MUL overflow detector.

Fixes #714

---
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/767)

### CODE REVIEW

**Comment by mossberg** [comment]
This is not quite ready yet, it should have a test for detecting a mul overflow.

**Comment by yan** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[manticore/ethereum.py, line 69 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/767#-L639-gPXLp3H923uLgS:-L639-gPXLp3H923uLgT:bnq39rx) ([raw file](https://github.com/trailofbits/manticore/blob/65ef3b0dd39336f92f208e0a2250b57713360f00/manticore/ethereum.py#L69)):*
> ```Python
>     @staticmethod
>     def _can_sub_overflow(state, arguments):
>         return state.can_be_true(arguments[1] > arguments[0])
> ```

Nit, but I believe it's underflow when dealing with subtraction.

---

*[manticore/ethereum.py, line 70 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/767#-L638no3JEQ_xSBvirvO:-L638no3JEQ_xSBvirvP:b4gh091) ([raw file](https://github.com/trailofbits/manticore/blob/65ef3b0dd39336f92f208e0a2250b57713360f00/manticore/ethereum.py#L70)):*
> ```Python
>     def _can_sub_overflow(state, arguments):
>         return state.can_be_true(arguments[1] > arguments[0])
> ```

These methods (for `add`, `mul`, and `sub`) should take the two arguments as individual parameters, or be general to n-ary functions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/767)*

**Comment by mossberg** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[manticore/ethereum.py, line 69 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/767#-L639-gPXLp3H923uLgS:-L63IXlGk5wfb6TjSxsN:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/65ef3b0dd39336f92f208e0a2250b57713360f00/manticore/ethereum.py#L69)):*
<details><summary><i>Previously, yan (Yan Ivnitskiy) wrote…</i></summary><blockquote>

Nit, but I believe it's underflow when dealing with subtraction.
</blockquote></details>

Done.

---

*[manticore/ethereum.py, line 70 at r2](https://reviewable.io:443/reviews/trailofbits/manticore/767#-L638no3JEQ_xSBvirvO:-L63IXQwzv_30d7V-NBS:b-896fix) ([raw file](https://github.com/trailofbits/manticore/blob/65ef3b0dd39336f92f208e0a2250b57713360f00/manticore/ethereum.py#L70)):*
<details><summary><i>Previously, yan (Yan Ivnitskiy) wrote…</i></summary><blockquote>

These methods (for `add`, `mul`, and `sub`) should take the two arguments as individual parameters, or be general to n-ary functions.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/767)*

**Comment by yan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/trailofbits/manticore/767#-:-L63IrSEwnhGYDJQjCtQ:bnfp4nl)*

**Pull request merged**
