### PR TITLE
added timeout support for ManticoreEVM

### PR DESCRIPTION
**Pull request by evgeniuz**
Fixes https://github.com/trailofbits/manticore/issues/1130

---
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/1186)

### CODE REVIEW

**Comment by evgeniuz** [comment]
Plan to try to add tests for this issue.

**Comment by mkosowsk** [comment]
Hi @evgeniuz how is progress coming along? Thanks!

**Comment by evgeniuz** [comment]
Sorry, was a little busy this week, will submit updated PR tomorrow (I have suspicion that current version sets timeout per single transaction, not whole invocation).

**Comment by evgeniuz** [comment]
Added timeout for solidity CLI runner (also, changed timeout handling in `run` method to avoid code duplication, now same decorator is used in both places).

**Comment by evgeniuz** [comment]
Added tests.

**Comment by evgeniuz** [comment]
Implemented according to spec (with test) and ready for review.

**Comment by disconnect3d** [comment]
We have a `timeout` config variable for smt solver:
https://github.com/trailofbits/manticore/blob/master/manticore/core/smtlib/solver.py#L36-L37

and we should add one for the overall execution too. This should also have the default value of 0. @evgeniuz can you add it?

**Comment by evgeniuz** [comment]
Added timeout to config.

**Pull request merged**
