### PR TITLE
Update Unicorn to 1.0.2rc1

### LINKED ISSUE #1434: Update Unicorn for better XMM instruction support
### OS / Environment
Official `trailofbits/manticore` docker image

### Manticore version
Version: 0.2.5

### Python version
Python 3.6.7

### Dependencies
asn1crypto==0.24.0
capstone==4.0.1
cryptography==2.1.4
cytoolz==0.9.0.1
eth-hash==0.2.0
eth-typing==2.1.0
eth-utils==1.5.2
future==0.17.1
idna==2.6
keyring==10.6.0
keyrings.alt==3.0
manticore==0.2.5
ply==3.11
prettytable==0.7.2
pycrypto==2.6.1
pyelftools==0.25
pyevmasm==0.2.0
pygobject==3.26.1
pysha3==1.0.2
pyxdg==0.25
PyYAML==5.1
rlp==1.1.0
SecretStorage==2.3.1
six==1.11.0
toolz==0.9.0
unicorn==1.0.1
z3-solver==4.8.5.0

### Summary of the problem
The current installation of Unicorn is too old to properly decode the following instruction
```
c5 f1 64 fc     vpcmpgtb        xmm7, xmm1, xmm4
```
and it kills Manticore during a run with
```
2019-05-15 19:58:53,586: [437] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffb5065f:        c5 f1 64 fc     vpcmpgtb        xmm7, xmm1, xmm4
2019-05-15 19:58:53,588: [437] m.n.c.abstractcpu:ERROR: Unimplemented instruction: 0x00007fffffb5065f:  c5 f1 64 fc     vpcmpgtb        xmm7, xmm1, xmm4
2019-05-15 19:58:53,590: [437] m.c.executor:ERROR: Exception: Invalid instruction (UC_ERR_INSN_INVALID)
```

### Step to reproduce the behavior
The version of unicorn installed can be invoked by running the following script with `python3 unicorn_fail.py` within the `trailofbits/manticore` docker image.
```
#!/usr/bin/env python
# Sample code for X86 of Unicorn. Nguyen Anh Quynh <aquynh@gmail.com>

from __future__ import print_function
from unicorn import *
from unicorn.x86_const import *

# This is the instruction that isn't supported with old Unicorn installed in Docker
X86_CODE64_XMM = b"\xc5\xf1\x64\xfc" # vpcmpgtb xmm7, xmm1, xmm4

# memory address where emulation starts
ADDRESS = 0x1000000

# callback for tracing basic blocks
def hook_block(uc, address, size, user_data):
    print(">>> Tracing basic block at 0x%x, block size = 0x%x" %(address, size))

def hook_code64(uc, address, size, user_data):
    print(">>> Tracing instruction at 0x%x, instruction size = 0x%x" %(address, size))
    rip = uc.reg_read(UC_X86_REG_RIP)
    print(">>> RIP is 0x%x" %rip);

def test_x86_64_XMM():
    print("Emulate x86_64 code")
    try:
        # Initialize emulator in X86-64bit mode
        mu = Uc(UC_ARCH_X86, UC_MODE_64)

        # map 2MB memory for this emulation
        mu.mem_map(ADDRESS, 2 * 1024 * 1024)

        # write machine code to be emulated to memory
        mu.mem_write(ADDRESS, X86_CODE64_XMM)

        # initialize machine registers
        mu.reg_write(UC_X86_REG_XMM1, 0x000102030405060708090a0b0c0d0e0f)
        mu.reg_write(UC_X86_REG_XMM4, 0x00102030405060708090a0b0c0d0e0f0)
        mu.reg_write(UC_X86_REG_XMM7, 0x00102030405060708090a0b0c0d0ffff)

        # tracing all basic blocks with customized callback
        mu.hook_add(UC_HOOK_BLOCK, hook_block)

        # tracing all instructions with customized callback
        mu.hook_add(UC_HOOK_CODE, hook_code64)

        try:
            # emulate machine code in infinite time
            mu.emu_start(ADDRESS, ADDRESS + len(X86_CODE64_XMM))
        except UcError as e:
            print("ERROR: %s" % e)

        # now print out some registers
        print(">>> Emulation done. Below is the CPU context")

        r_xmm1 = mu.reg_read(UC_X86_REG_XMM1)
        r_xmm4 = mu.reg_read(UC_X86_REG_XMM4)
        r_xmm7 = mu.reg_read(UC_X86_REG_XMM7)
        print(">>> XMM0 = 0x%.64x" %r_xmm1)
        print(">>> XMM0 = 0x%.64x" %r_xmm4)

    except UcError as e:
        print("ERROR: %s" % e)

if __name__ == '__main__':
    print("=" * 35)
    test_x86_64_XMM()
```

### Expected behavior
With the latest version of Unicorn (from `master`) I don't get the `UC_ERR_INSN_INVALID` error.
```
Emulate x86_64 code
>>> Tracing basic block at 0x1000000, block size = 0x4
>>> Tracing instruction at 0x1000000, instruction size = 0x4
>>> RIP is 0x1000000
>>> Emulation done. Below is the CPU context
>>> XMM0 = 0x00000000000000000000000000000000000102030405060708090a0b0c0d0e0f
>>> XMM0 = 0x0000000000000000000000000000000000102030405060708090a0b0c0d0e0f0
```

### Actual behavior
With the version of Unicorn installed in the Docker image I get the error.
```
Emulate x86_64 code
>>> Tracing basic block at 0x1000000, block size = 0x3
>>> Tracing instruction at 0x1000000, instruction size = 0xf1f1f1f1
>>> RIP is 0x1000000
ERROR: Invalid instruction (UC_ERR_INSN_INVALID)
>>> Emulation done. Below is the CPU context
>>> XMM0 = 0x00000000000000000000000000000000000102030405060708090a0b0c0d0e0f
>>> XMM0 = 0x0000000000000000000000000000000000102030405060708090a0b0c0d0e0f0
```

### Any relevant logs
Output of unicorn script with error is posted above.

I tried to update and install Unicorn from `master` and run Manticore, but I get segfault on the first unimplemented instruction:
```
2019-05-15 21:00:55,666: [690] m.n.c.abstractcpu:WARNING: Unimplemented instruction: 0x00007fffffdc1864:        0f 16 85 68 ff ff ff    movhps  xmm0, qword ptr [rbp - 0x98]
./manticore_process.sh: line 30:   690 Segmentation fault  
```

I'm also not sure where Unicorn added support for this instruction.

### PR DESCRIPTION
**Pull request by ekilmer**
Unicorn still doesn't like writing to the `FS` register.

closes #1434

### CODE REVIEW

**Comment by ekilmer** [comment]
Actually, there are some comments about Manticore code using workarounds for bugs in Unicorn https://github.com/trailofbits/manticore/issues/1434#issuecomment-493122462

Might be worth looking into the above before merging?

**Comment by ekilmer** [comment]
Seems the `XMM` and `YMM` registers are still buggy/not matching when they're enabled in the tests

**Comment by ehennenfent** [comment]
> Seems the `XMM` and `YMM` registers are still buggy/not matching when they're enabled in the tests

@ekilmer What makes you say this? I've commented out the workaround in `fallback_emulator.py` and the tests still seem to pass for me. They've already been removed from `emulator.py`, which makes me think that they haven't been necessary for a while.

**Comment by ekilmer** [comment]
@ehennenfent I get this diff when adding the `XMM` and `YMM` registers to the test

```
======================================================================
FAIL: test_register_comparison (tests.native.test_unicorn_concrete.ManticornTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/manticore/tests/native/test_unicorn_concrete.py", line 131, in test_register_comparison
    self.assertDictEqual(concrete_regs_vals, normal_regs_vals)
AssertionError: {'YMM[26 chars]M2': 4722366482869645213696, 'RBX': 0, 'XMM10'[1151 chars]': 0} != {'YMM[26 chars]M2': 71776119061217280, 'RBX': 0, 'XMM10': 308[1139 chars]': 0}
  {'AF': False,
   'CF': False,
   'CS': 35,
   'DF': False,
   'DS': 43,
   'ES': 43,
   'FP0': (0, 0),
   'FP1': (0, 0),
   'FP2': (0, 0),
   'FP3': (0, 0),
   'FP4': (0, 0),
   'FP5': (0, 0),
   'FP6': (0, 0),
   'FP7': (0, 0),
   'FPCW': 0,
   'FPSW': 0,
   'FS': 99,
   'GS': 0,
   'IF': False,
   'OF': False,
   'R10': 18446744073709551568,
   'R12': 7056528,
   'R13': 7056528,
   'R14': 7058176,
   'R15': 7048304,
   'R8': 60,
   'R9': 231,
   'RAX': 231,
   'RBP': 140737488354576,
   'RBX': 0,
   'RDI': 0,
   'RDX': 8,
   'RIP': 4403209,
   'RSI': 0,
   'RSP': 140737488354576,
   'SF': False,
   'SS': 43,
-  'XMM0': 20203182645340859218113236893695,
-  'XMM1': 137504372832221650227709151979224760320,
+  'XMM0': 20203181441137406086353707335680,
+  'XMM1': 49374304219900875090764158725393818917,
   'XMM10': 308276084001730439550074880,
   'XMM11': 0,
   'XMM12': 0,
   'XMM13': 0,
   'XMM14': 0,
   'XMM15': 0,
-  'XMM2': 4722366482869645213696,
+  'XMM2': 71776119061217280,
   'XMM3': 0,
   'XMM4': 20203181441137406086353707335680,
   'XMM5': 0,
   'XMM6': 0,
   'XMM7': 0,
   'XMM8': 0,
   'XMM9': 5172014448931175958106549077934080,
-  'YMM0': 20203182645340859218113236893695,
-  'YMM1': 137504372832221650227709151979224760320,
+  'YMM0': 20203181441137406086353707335680,
+  'YMM1': 49374304219900875090764158725393818917,
   'YMM10': 308276084001730439550074880,
   'YMM11': 0,
   'YMM12': 0,
   'YMM13': 0,
   'YMM14': 0,
   'YMM15': 0,
-  'YMM2': 4722366482869645213696,
+  'YMM2': 71776119061217280,
   'YMM3': 0,
   'YMM4': 20203181441137406086353707335680,
   'YMM5': 0,
   'YMM6': 0,
   'YMM7': 0,
   'YMM8': 0,
 ```

**Pull request merged**
